class Wordlist:
    Content = [
        "users","profiles","admins","admin","administrator","administrators",
        "mods","moderator","moderators","superadmin","superadmins","root",
        "operators","operator","staff","employees","employee","agents","agent",
        "vendors","vendor","partners","partner","coach_profiles","coaches","admin_profiles",
        "student_profiles","recruiter_profiles","recruiters","students","clients","client","guests",
        "guest","visitors","visitor","members","member","memberships","accounts","account",
        "customers","customer","company","players","player","owners","owner","managers",
        "manager","developers","developer","contractors","referrers","referrer","contractor","users_v2",
        "user_accounts","user_profiles","user_profile","user_info","user_infos","user_data","user_settings",
        "user_preferences","user_roles","user_tokens","user_sessions","v_session","user_logs",
        "user_activity","user_events","user_metadata","user_details","user_contacts",
        "user_addresses","user_payments","user_subscriptions","user_invoices",
        "user_notifications","user_messages","user_files","user_uploads",
        "user_images","user_avatars","user_permissions","user_groups","user_claims",
        "user_devices","user_keys","user_secrets","user_credentials","user_2fa",
        "user_mfa","user_oauth","user_social","user_kyc","user_verifications",
        "user_bans","user_reports","user_feedback","user_surveys","user_referrals",
        "user_rewards","user_points","user_badges","user_achievements",

        "calls","site_settings","app_settings","sessions","session","tokens","token","auth","auth_tokens","auth_sessions","visitor_sessions",
        "auth_codes","auth_logs","access_tokens","refresh_tokens","bearer_tokens",
        "jwt_tokens","api_tokens","api_keys","api_secrets","api_credentials",
        "oauth_tokens","oauth_clients","oauth_codes","oauth_sessions","sso_tokens",
        "sso_sessions","mfa_secrets","mfa_codes","mfa_devices","totp_secrets",
        "recovery_codes","reset_tokens","verification_tokens","invite_tokens",
        "magic_links","passwordless_tokens","login_attempts","login_logs",
        "logout_logs","auth_events","auth_attempts","auth_history","password_resets",
        "password_hashes","password_history","passwords","credentials","secrets",
        "private_keys","public_keys","signing_keys","encryption_keys","keys","key","ws_kw_keywords",
        "mv_word_counts","v_request_requester","os_platforms",

        "roles","role","permissions","permission","privileges","privilege",
        "capabilities","policies","policy","access_control","acl","rbac",
        "scopes","scope","grants","grant","entitlements","entitlement",
        "groups","group","teams","team","organizations","organization","orgs",
        "org","workspaces","workspace","tenants","tenant","namespaces",

        "payments","payment","transactions","transaction","invoices","invoice",
        "billing","subscriptions","subscription","plans","plan","pricing",
        "orders","order","order_items","order_history","cart","carts","platform_orders",
        "checkouts","checkout","refunds","refund","chargebacks","chargeback",
        "disputes","dispute","payouts","payout","withdrawals","withdrawal",
        "deposits","deposit","transfers","transfer","wallets","wallet",
        "balances","balance","credits","credit","debits","debit",
        "credit_cards","cards","card","ccs","ibans","iban","bank_accounts",
        "bank_account","payment_methods","payment_profiles","billing_info",
        "billing_address","billing_history","tax_records","tax","vat",
        "receipts","receipt","quotes","quote","devis","estimates","estimate",
        "budgets","budget","expenses","expense","revenue","revenues",
        "earnings","earning","commissions","commission","fees","fee",
        "discounts","discount","coupons","coupon","promo_codes","vouchers",
        "voucher","gift_cards","gift_card","crypto_wallets","crypto_transactions",

        "psartech_contact_requests","emails","email","mails","mail","addresses","address","phone_numbers",
        "phones","phone","names","ssn","national_ids","passports","passport",
        "id_cards","id_documents","kyc","kyc_documents","kyc_verifications",
        "identity","identities","pii","personal_data","private_data",
        "sensitive_data","gdpr_data","dob","birth_dates","gender","genders",
        "nationalities","nationality","locations","location","gps_data",
        "ip_addresses","ip_logs","device_fingerprints","biometrics","face_data",

        "content","folders","files","articles","article","posts","post","follows","follow","pages","page",
        "blogs","blog","comments","comment","reviews","review","ratings",
        "rating","tags","tag","categories","category","topics","topic",
        "threads","thread","forums","forum","messages","message","chats",
        "chat","conversations","conversation","inbox","outbox","drafts",
        "draft","announcements","announcement","newsletters","newsletter",
        "campaigns","campaign","banners","banner","ads","ad","media",
        "files","file","uploads","upload","attachments","attachment",
        "images","image","videos","video","audio","documents","document",
        "pdfs","pdf","exports","export","imports","import","backups","backup",

        "settings","setting","internal_settings","system_config","config",
        "configurations","configuration","options","option","preferences",
        "preference","parameters","parameter","flags","flag","features",
        "feature","feature_flags","experiments","experiment","ab_tests",
        "ab_test","environment","environments","env_vars","variables",
        "variable","constants","constant","properties","property",
        "metadata","schema","schemas","migrations","migration","seeds",
        "seed","fixtures","fixture","templates","template","themes","theme",
        "layouts","layout","widgets","widget","components","component",
        "modules","module","plugins","plugin","extensions","extension",
        "integrations","integration","webhooks","webhook","crons","cron",
        "jobs","job","queues","queue","workers","worker","tasks","task",
        "schedules","schedule","events","event","triggers","trigger",
        "actions","action","workflows","workflow","pipelines","pipeline",

        "logs","log","audit_logs","audit_log","error_logs","error_log",
        "access_logs","access_log","activity_logs","activity_log","event_logs",
        "event_log","system_logs","system_log","security_logs","security_log",
        "debug_logs","debug_log","app_logs","app_log","request_logs",
        "request_log","response_logs","api_logs","api_log","change_logs",
        "change_log","history","histories","archives","archive","snapshots",
        "snapshot","traces","trace","metrics","metric","stats","stat",
        "analytics","analytic","reports","report","dashboards","dashboard",
        "monitoring","alerts","alert","incidents","incident","outages","outage",
        "errors","error","exceptions","exception","crashes","crash",
        "performance","latency","throughput","uptime","downtime",

        "honeypot","honeypots","blacklist","blacklists","whitelist","whitelists",
        "blocklist","blocklists","banned_ips","banned_users","bans","ban",
        "rate_limits","rate_limit","throttles","throttle","captcha_logs",
        "fraud_logs","fraud","abuse","abuse_reports","spam","spam_reports",
        "vulnerabilities","vulnerability","security_events","intrusions",
        "intrusion","threats","threat","malware","suspicious_activity",
        "flagged_users","blocked_users","suspended_accounts",

        "notifications","notification","emails_sent","email_logs","email_queue",
        "sms","sms_logs","sms_queue","shipping_quotes","push_notifications","push_tokens",
        "device_tokens","fcm_tokens","apns_tokens","mailchimp_logs",
        "sendgrid_logs","twilio_logs","contacts","contact","leads","lead",
        "prospects","prospect","mailing_lists","mailing_list","subscribers",
        "subscriber","unsubscribes","unsubscribe","bounces","bounce",

        "source","sources","products","product","items","item","inventory","inventories",
        "stock","stocks","warehouses","warehouse","shipping","shippings",
        "shipments","shipment","tracking","deliveries","delivery",
        "returns","return","missions","exchanges","exchange","collections","collection",
        "catalogs","catalog","skus","sku","variants","variant",
        "attributes","attribute","specifications","specification",
        "wishlists","wishlist","favorites","favorite","compare",

        "ideas","votes","vote","polls","poll","surveys","survey",
        "forms","form","form_submissions","responses","response",
        "bookings","booking","reservations","reservation","appointments",
        "appointment","calendars","calendar","events_calendar","slots",
        "slot","availability","availabilities","tickets","ticket",
        "issues","issue","bugs","bug","features_requests","feedback",
        "support_tickets","support","help_desk","helpdesk","kb_articles",
        "knowledge_base","faqs","faq","documentation","docs",
        "projects","project","tasks_board","kanban","sprints","sprint",
        "milestones","milestone","releases","release","versions","version",
        "changelogs","changelog","roadmap","roadmaps",

        "licenses","license","licence","licences","serial_keys","activation_keys",
        "product_keys","domains","domain","subdomains","subdomain",
        "certificates","certificate","ssl_certs","ssl","dns_records",

        "v2_site_content","transporter_vehicles","transporter_zones","workshop_services","referrals","referral",
        "affiliates","affiliate","partnerships","partnership","deals","deal",
        "contracts","contract","agreements","agreement","terms","term",
        "privacy","gdpr_requests","data_exports","data_deletions",
        "onboarding","offboarding","invitations","invitation","waitlist",
        "waitlists","beta_users","early_access","signups","signup",
        "registrations","registration","verifications","verification",
        "approvals","approval","rejections","rejection","reviews_queue",
        "moderation","flags","reported_content","takedowns","takedown","neko_coins",
        "membership_benefits_config",
    ]